export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const CLEAR_SEARCH = "CLEAR_SEARCH"

export const UPDATE_USER_FILE = "UPDATE_USER_FILE"

export const LOGOUT =  'LOGOUT';

